//! Emit the Bevy Scene Notation (`.bsn`): per-submesh entities (a `Transform`, the baked
//! `RaytracingMesh3d`, and an inline `SolariMaterial3d`) wrapped in the scene envelope.

use std::fmt::Write as _;

use crate::dedup::V3;
use crate::img;

/// Wrap the entity list in the `#Name / Children [...]` scene envelope. No root
/// `Transform`: a patch component would stomp the instance entity's placement.
pub fn scene(scene_name: &str, entities: &str) -> String {
    scene_with_root(scene_name, "", entities)
}

/// Like [`scene`], but emits `root_components` (newline-terminated patch lines) on the root entity
/// between the `#Name` and its `Children` — e.g. an animation marker. Empty `root_components` is
/// identical to [`scene`].
pub fn scene_with_root(scene_name: &str, root_components: &str, entities: &str) -> String {
    format!(
        "// Generated by solari_bsn. Do not edit by hand.\n\
         #{scene_name}\n\
         {root_components}\
         bevy_ecs::hierarchy::Children [\n{entities}]\n"
    )
}

/// Append one submesh's `.bsn` entity (comma-terminated): a `Transform` placing the local-space
/// geometry at its world `translation`, the baked `RaytracingMesh3d`, and an inline `SolariMaterial3d`.
#[allow(clippy::too_many_arguments)]
pub fn write_entity(
    out: &mut String,
    asset_prefix: &str,
    mesh_stem: &str,
    material: Option<&tobj::Material>,
    is_cutmask: bool,
    displacement_maps: &[(String, String)],
    translation: V3,
    rotation: [f64; 4],
    scale: f64,
) {
    // `f` emits fixed-point floats (the lexer rejects `{:?}`'s scientific notation for tiny
    // quaternion terms). Rotation/scale are written only when non-trivial (instances); owners /
    // singletons get a translation-only `Transform` and the loader defaults rotation → identity,
    // scale → one.
    // `Transform`'s fields are the precision aliases `TVec3`/`TQuat`; the fork builds at f64, so
    // the `.bsn` MUST name `glam::DVec3`/`glam::DQuat` — an f32 `glam::Vec3` literal fails to
    // coerce into the f64 field and silently zeroes it (collapsing the instance to a point).
    let mut transform = format!(
        "translation: glam::DVec3 {{ x: {}, y: {}, z: {} }}",
        f(translation[0] as f32), f(translation[1] as f32), f(translation[2] as f32),
    );
    let [qw, qx, qy, qz] = rotation;
    if qx * qx + qy * qy + qz * qz > 1e-10 {
        let _ = write!(
            transform,
            ", rotation: glam::DQuat {{ x: {}, y: {}, z: {}, w: {} }}",
            f(qx as f32), f(qy as f32), f(qz as f32), f(qw as f32),
        );
    }
    if (scale - 1.0).abs() > 1e-9 {
        let s = f(scale as f32);
        let _ = write!(transform, ", scale: glam::DVec3 {{ x: {s}, y: {s}, z: {s} }}");
    }
    let _ = write!(
        out,
        "    bevy_transform::components::transform::Transform {{ {transform} }}\n    \
         bevy_solari::bindings::types::RaytracingMesh3d(\"{asset_prefix}/meshes/{mesh_stem}.cluster_mesh\")\n    \
         bevy_solari::material::SolariMaterial3d(bevy_solari::material::StandardSolariMaterial {{{}}}),\n\n",
        material_fields(asset_prefix, material, is_cutmask, displacement_maps),
    );
}

/// Inline `SolariMaterial` field list for the `.bsn`. Absent fields fall back to the material's
/// defaults (e.g. an omitted `base_color_texture` stays `None`).
fn material_fields(
    asset_prefix: &str,
    material: Option<&tobj::Material>,
    is_cutmask: bool,
    displacement_maps: &[(String, String)],
) -> String {
    let Some(material) = material else {
        return String::new();
    };
    let mut fields = String::new();

    // NOTE: `base_color` (a `Color::LinearRgba(..)` enum tuple variant) is deferred. Textured
    // materials carry their look via `base_color_texture`.
    if let Some(tex) = material.diffuse_texture.as_deref() {
        let _ = write!(fields, " base_color_texture: \"{asset_prefix}/textures/{}\",", img::basename(tex));
        // Displacement (depth) map matched by name — the MTL doesn't reference it. Carried on the
        // material since glTF can't; consumed by tessellation (scale/bias tuned when it renders).
        if let Some(disp) = img::match_displacement(tex, displacement_maps) {
            let _ = write!(fields, " depth_map: \"{asset_prefix}/textures/{disp}\",");
        }
    }
    if let Some(tex) = material.normal_texture.as_deref() {
        let _ = write!(fields, " normal_map_texture: \"{asset_prefix}/textures/{}\",", img::basename(tex));
    }
    // Genuine alpha cutout (foliage): emit `AlphaMode::Mask` so the ray tracer any-hit-tests it.
    // The fully-qualified definition module is what the dynamic loader resolves (`Mask` is an enum
    // tuple variant); the cutoff matches the cutmask classifier.
    if is_cutmask {
        let _ = write!(
            fields,
            " alpha_mode: bevy_material::alpha::AlphaMode::Mask({:?}),",
            img::MASK_CUTOFF,
        );
    }
    fields
}

/// Append one entity built from a pre-formatted `SolariMaterial` field list and a full
/// translation/rotation/scale `Transform` (the glTF path: node world transforms can carry
/// non-uniform scale, so all three are always written).
pub fn write_entity_trs(
    out: &mut String,
    asset_prefix: &str,
    mesh_stem: &str,
    material_fields: &str,
    name: &str,
    translation: [f32; 3],
    rotation: [f32; 4],
    scale: [f32; 3],
) {
    let [tx, ty, tz] = translation;
    let [qx, qy, qz, qw] = rotation;
    let [sx, sy, sz] = scale;
    // Entity `Name` (source `Node.Material`), for debugging/authoring. Constructs via the loader's
    // `String -> HashedStr` conversion (registered by `SolariTransformPlugin`).
    if !name.is_empty() {
        let _ = write!(out, "    bevy_ecs::name::Name(\"{}\")\n", name.replace('"', "'"));
    }
    let _ = write!(
        out,
        "    bevy_transform::components::transform::Transform {{ \
         translation: glam::DVec3 {{ x: {}, y: {}, z: {} }}, \
         rotation: glam::DQuat {{ x: {}, y: {}, z: {}, w: {} }}, \
         scale: glam::DVec3 {{ x: {}, y: {}, z: {} }} }}\n    \
         bevy_solari::bindings::types::RaytracingMesh3d(\"{asset_prefix}/meshes/{mesh_stem}.cluster_mesh\")\n    \
         bevy_solari::material::SolariMaterial3d(bevy_solari::material::StandardSolariMaterial {{{material_fields}}}),\n\n",
        f(tx), f(ty), f(tz),
        f(qx), f(qy), f(qz), f(qw),
        f(sx), f(sy), f(sz),
    );
}

/// Format an f32 as a `.bsn` float literal: fixed-point (never scientific — the lexer rejects
/// exponents like `1e-7`) with a decimal point, trailing zeros trimmed. 7 decimals is ample for
/// metre-scale translations, quaternions, and scales.
pub(crate) fn f(v: f32) -> String {
    let s = format!("{v:.7}");
    let s = s.trim_end_matches('0');
    if s.ends_with('.') {
        format!("{s}0")
    } else {
        s.to_string()
    }
}
