//! Hoverboard importer: bake the ZR-09 hoverboard glb to `.cluster_mesh` + a `.bsn`.
//!
//! Unlike every other importer here the source is AUTHORED, not downloaded — it's generated by
//! `/mnt/code/p/assets/hoverboard/build/*.py` and exported texture-free on purpose. The materials
//! ship as scalar factors (base_color/metallic/roughness/emissive) rather than maps, so shading
//! costs a `GpuMaterial` fetch and no texture reads. `meshes/` is written; `textures/` stays empty.
//!
//!   cargo run --release -p hoverboard_import -- \
//!     raw/hoverboard/hoverboard.glb assets/hoverboard

use std::path::PathBuf;

use clap::Parser;
use solari_bsn::{bake_gltf_scene, GltfConfig};

#[derive(Parser)]
#[command(about = "Bake the hoverboard glb → .cluster_mesh + .bsn (texture-free)")]
struct Args {
    /// Source `.glb` from `hb_export.py`.
    glb: PathBuf,
    /// Output asset directory (`meshes/` and the `.bsn`).
    out_dir: PathBuf,
    /// Asset-server-relative prefix the `.bsn` uses to reference meshes.
    #[arg(default_value = "hoverboard")]
    asset_prefix: String,
    /// Re-bake `.cluster_mesh` files even if they already exist.
    #[arg(long)]
    replace: bool,
}

/// Fallback emitter radiance in NITS, keyed on material name. The exporter splits each neon's
/// radiance into a unit `emissiveFactor` + `KHR_materials_emissive_strength`, so this should never
/// fire — it's a backstop for the case where a Blender version drops the strength extension and
/// every strip would otherwise import at 1.0.
///
/// These are physical, not the scene-relative values the .blend renders with: Solari exposes at
/// `Exposure::BLENDER` (EV100 9.7, a ~0.001 multiplier), so single-digit radiance reads as black.
/// Mirrors `hb_core.NEON_RADIANCE * EMISSIVE_NITS_SCALE`.
fn emissive_nits(material: &str) -> f32 {
    match material {
        "M_Neon_Cyan" => 1700.0,
        "M_Neon_Magenta" => 1800.0,
        "M_Neon_Violet" => 1800.0,
        "M_Neon_Hot" => 5200.0,
        "M_Neon_Amber" => 800.0,
        "M_HoloPanel" => 345.0,
        "M_HoloBar" => 1300.0,
        _ => 1.0,
    }
}

fn main() {
    let args = Args::parse();

    let cfg = GltfConfig {
        gltf_path: args.glb,
        out_dir: args.out_dir,
        asset_prefix: args.asset_prefix,
        scene_name: "hoverboard".to_string(),
        replace: args.replace,
        root_components: String::new(),
        emissive_nits: Some(emissive_nits),
        erode_px: solari_bsn::mesh::DEFAULT_ERODE_PX,
        omm_subdiv: solari_bsn::mesh::DEFAULT_OMM_SUBDIV,
    };
    bake_gltf_scene(&cfg);
}
