//! The baked `.bsn`: a `#Name` root whose `Children` are the baked entities (a `Transform`, the
//! mesh as `AuroraMesh3d("….aurora_mesh")`, an inline `AuroraMaterial` in `AuroraMaterial3d`).
//! Built as a [`bevy::bsn`] document and printed by its printer, so the syntax is the loader's.

use bevy::bsn::{
    BsnDocument, BsnNodeId, BsnNodeKind, BsnPatchPrefix, BsnPath, BsnValue, BsnValueId, PatchBody,
};

use crate::dedup::V3;
use crate::img;

/// A component, or a value inside one.
#[derive(Clone, Debug)]
pub enum Value {
    Float(f32),
    Int(i64),
    Bool(bool),
    Str(String),
    /// A unit struct or unit enum variant, by type path.
    Path(&'static str),
    Struct(&'static str, Vec<(&'static str, Value)>),
    Tuple(&'static str, Vec<Value>),
    List(Vec<Value>),
}

/// One baked entity: its components, then its children.
#[derive(Clone, Debug, Default)]
pub struct Entity {
    pub components: Vec<Value>,
    pub children: Vec<Entity>,
}

/// The scene: `#scene_name`, the `root` components, and `children` under `Children`. No root
/// `Transform`: a patch component would stomp the instance entity's placement. Every entity gets
/// a `Visibility`, and every one below the root a `Transform`, so propagation runs unbroken from
/// the instance down.
pub fn scene(scene_name: &str, mut root: Vec<Value>, mut children: Vec<Entity>) -> String {
    add_missing(&mut root, VISIBILITY, || Value::Path(VISIBILITY_INHERITED));
    for child in &mut children {
        make_spatial(child);
    }
    let mut doc = BsnDocument::new();
    let root = lower_entity(&mut doc, Some(scene_name.to_string()), root, children);
    doc.push_root(root);
    format!(
        "// Generated by aurora_bsn. Do not edit by hand.\n{}",
        bevy::bsn::print_document(&doc)
    )
}

const TRANSFORM: &str = "bevy_transform::components::transform::Transform";
const VISIBILITY: &str = "bevy_camera::visibility::Visibility";
const VISIBILITY_INHERITED: &str = "bevy_camera::visibility::Visibility::Inherited";

/// Give `entity` and everything below it a `Transform` and a `Visibility`.
fn make_spatial(entity: &mut Entity) {
    add_missing(&mut entity.components, TRANSFORM, || Value::Path(TRANSFORM));
    add_missing(&mut entity.components, VISIBILITY, || Value::Path(VISIBILITY_INHERITED));
    for child in &mut entity.children {
        make_spatial(child);
    }
}

fn add_missing(components: &mut Vec<Value>, type_path: &str, make: impl FnOnce() -> Value) {
    let has = components.iter().any(|component| match component {
        Value::Path(p) => *p == type_path || p.strip_prefix(type_path).is_some_and(|rest| rest.starts_with("::")),
        Value::Struct(p, _) | Value::Tuple(p, _) => *p == type_path,
        _ => false,
    });
    if !has {
        components.push(make());
    }
}

fn lower_entity(
    doc: &mut BsnDocument,
    name: Option<String>,
    components: Vec<Value>,
    children: Vec<Entity>,
) -> BsnNodeId {
    let patches = components
        .into_iter()
        .map(|component| lower_patch(doc, component))
        .collect();
    let mut relations = Vec::new();
    if !children.is_empty() {
        let entities = children
            .into_iter()
            .map(|child| lower_entity(doc, None, child.components, child.children))
            .collect();
        relations.push(doc.push_node(BsnNodeKind::Relation {
            target_symbol: path("bevy_ecs::hierarchy::Children"),
            entities,
        }));
    }
    doc.push_node(BsnNodeKind::Entity {
        name,
        name_span: None,
        base: None,
        base_span: None,
        patches,
        relations,
    })
}

fn lower_patch(doc: &mut BsnDocument, component: Value) -> BsnNodeId {
    let (symbol, body) = match component {
        Value::Path(p) => (p, PatchBody::Unit),
        Value::Struct(p, fields) => (p, PatchBody::Struct(lower_fields(doc, fields))),
        Value::Tuple(p, items) => (
            p,
            PatchBody::Tuple(items.into_iter().map(|v| lower_value(doc, v)).collect()),
        ),
        other => panic!("a component is a unit, struct or tuple struct, not {other:?}"),
    };
    doc.push_patch(BsnPatchPrefix::FromTemplate, path(symbol), body)
}

fn lower_fields(
    doc: &mut BsnDocument,
    fields: Vec<(&'static str, Value)>,
) -> Vec<(String, BsnValueId)> {
    fields
        .into_iter()
        .map(|(name, value)| (name.to_string(), lower_value(doc, value)))
        .collect()
}

fn lower_value(doc: &mut BsnDocument, value: Value) -> BsnValueId {
    let value = match value {
        // The f32's shortest decimal, so `0.1` prints as `0.1` rather than its f64 widening.
        Value::Float(v) => BsnValue::Float(v.to_string().parse().expect("f32 display parses")),
        Value::Int(i) => BsnValue::Int(i.into()),
        Value::Bool(b) => BsnValue::Bool(b),
        Value::Str(s) => BsnValue::String(s),
        Value::Path(p) => BsnValue::Path(path(p)),
        Value::Struct(p, fields) => BsnValue::Struct(path(p), lower_fields(doc, fields)),
        Value::Tuple(p, items) => BsnValue::NamedTuple(
            path(p),
            items.into_iter().map(|v| lower_value(doc, v)).collect(),
        ),
        Value::List(items) => {
            BsnValue::List(items.into_iter().map(|v| lower_value(doc, v)).collect())
        }
    };
    doc.push_value(value)
}

fn path(type_path: &str) -> BsnPath {
    BsnPath::from_type_path(type_path).expect("a valid type path")
}

pub fn name(name: &str) -> Value {
    Value::Tuple("bevy_ecs::name::Name", vec![Value::Str(name.to_string())])
}

pub fn vec3([x, y, z]: [f32; 3]) -> Value {
    Value::Struct(
        "glam::Vec3",
        vec![("x", Value::Float(x)), ("y", Value::Float(y)), ("z", Value::Float(z))],
    )
}

/// `[x, y, z, w]`.
pub fn quat([x, y, z, w]: [f32; 4]) -> Value {
    Value::Struct(
        "glam::Quat",
        vec![
            ("x", Value::Float(x)),
            ("y", Value::Float(y)),
            ("z", Value::Float(z)),
            ("w", Value::Float(w)),
        ],
    )
}

/// A `Transform`; rotation `[x, y, z, w]`. Absent parts keep the loader's default.
pub fn transform(
    translation: [f32; 3],
    rotation: Option<[f32; 4]>,
    scale: Option<[f32; 3]>,
) -> Value {
    let mut fields = vec![("translation", vec3(translation))];
    if let Some(rotation) = rotation {
        fields.push(("rotation", quat(rotation)));
    }
    if let Some(scale) = scale {
        fields.push(("scale", vec3(scale)));
    }
    Value::Struct("bevy_transform::components::transform::Transform", fields)
}

pub fn mesh(asset_prefix: &str, stem: &str) -> Value {
    Value::Tuple(
        "bevy_aurora::mesh::AuroraMesh3d",
        vec![Value::Str(format!("{asset_prefix}/meshes/{stem}.aurora_mesh"))],
    )
}

/// An inline `AuroraMaterial`; absent fields keep the material's defaults.
pub fn material(fields: Vec<(&'static str, Value)>) -> Value {
    Value::Tuple(
        "bevy_aurora::material::AuroraMaterial3d",
        vec![Value::Struct("bevy_aurora::material::AuroraMaterial", fields)],
    )
}

/// Collision geometry, by name only: `bevy_aurora::collision` has no physics engine, and a scene
/// that named one could not be opened by anything that did not have it.
pub fn collider(asset_prefix: &str, stem: &str) -> Value {
    Value::Tuple(
        "bevy_aurora::collision::CollisionMesh",
        vec![Value::Str(format!("{asset_prefix}/meshes/{stem}.collider"))],
    )
}

/// A separately baked scene, instanced here.
pub fn scene_ref(bsn_path: &str) -> Value {
    Value::Tuple(
        "bevy_scene::scene_patch::ScenePatchInstance",
        vec![Value::Str(bsn_path.to_string())],
    )
}

/// A skinned mesh's joint palette by name, in the skin's joint order.
pub fn skin_joints(joints: Vec<String>) -> Value {
    Value::Tuple(
        "bevy_aurora::skinning::SkinJointsByName",
        vec![Value::List(joints.into_iter().map(Value::Str).collect())],
    )
}

pub fn linear_rgba([red, green, blue, alpha]: [f32; 4]) -> Value {
    Value::Struct(
        "bevy_color::linear_rgba::LinearRgba",
        vec![
            ("red", Value::Float(red)),
            ("green", Value::Float(green)),
            ("blue", Value::Float(blue)),
            ("alpha", Value::Float(alpha)),
        ],
    )
}

/// `base_color` is a `Color` enum, so it takes the tuple-variant form.
pub fn color_linear(rgba: [f32; 4]) -> Value {
    Value::Tuple("bevy_color::color::Color::LinearRgba", vec![linear_rgba(rgba)])
}

pub fn color_srgba([red, green, blue, alpha]: [f32; 4]) -> Value {
    Value::Tuple(
        "bevy_color::color::Color::Srgba",
        vec![Value::Struct(
            "bevy_color::srgba::Srgba",
            vec![
                ("red", Value::Float(red)),
                ("green", Value::Float(green)),
                ("blue", Value::Float(blue)),
                ("alpha", Value::Float(alpha)),
            ],
        )],
    )
}

/// Alpha cutout, so the ray tracer any-hit-tests the surface.
pub fn alpha_mask(cutoff: f32) -> Value {
    Value::Tuple("bevy_aurora::material::AlphaMode::Mask", vec![Value::Float(cutoff)])
}

/// One OBJ submesh: a `Transform` placing the local-space geometry at its world `translation`,
/// the baked mesh, and its material. Rotation/scale are written only when non-trivial (instances).
#[allow(clippy::too_many_arguments)]
pub fn obj_entity(
    asset_prefix: &str,
    mesh_stem: &str,
    material: Option<&tobj::Material>,
    is_cutmask: bool,
    displacement_maps: &[(String, String)],
    translation: V3,
    rotation: [f64; 4],
    scale: f64,
) -> Entity {
    let [qw, qx, qy, qz] = rotation;
    let rotation = (qx * qx + qy * qy + qz * qz > 1e-10)
        .then(|| [qx as f32, qy as f32, qz as f32, qw as f32]);
    let scale = ((scale - 1.0).abs() > 1e-9).then(|| [scale as f32; 3]);
    Entity {
        components: vec![
            transform(translation.map(|v| v as f32), rotation, scale),
            mesh(asset_prefix, mesh_stem),
            self::material(material_fields(
                asset_prefix,
                material,
                is_cutmask,
                displacement_maps,
            )),
        ],
        children: Vec::new(),
    }
}

/// An OBJ material's `AuroraMaterial` fields. Absent fields fall back to the material's defaults
/// (e.g. an omitted `base_color_texture` stays `None`).
pub fn material_fields(
    asset_prefix: &str,
    material: Option<&tobj::Material>,
    is_cutmask: bool,
    displacement_maps: &[(String, String)],
) -> Vec<(&'static str, Value)> {
    let Some(material) = material else {
        return Vec::new();
    };
    let mut fields = Vec::new();
    // `base_color` is deferred: textured materials carry their look via `base_color_texture`.
    if let Some(tex) = material.diffuse_texture.as_deref() {
        fields.push((
            "base_color_texture",
            Value::Str(format!("{asset_prefix}/textures/{}", img::basename(tex))),
        ));
        // Displacement (depth) map matched by name -- the MTL doesn't reference it. Consumed by
        // tessellation.
        if let Some(disp) = img::match_displacement(tex, displacement_maps) {
            fields.push(("depth_map", Value::Str(format!("{asset_prefix}/textures/{disp}"))));
        }
    }
    if let Some(tex) = material.normal_texture.as_deref() {
        fields.push((
            "normal_map_texture",
            Value::Str(format!("{asset_prefix}/textures/{}", img::basename(tex))),
        ));
    }
    if is_cutmask {
        fields.push(("alpha_mode", alpha_mask(img::MASK_CUTOFF)));
    }
    fields
}

/// One entity with a full translation/rotation/scale `Transform` (the glTF path: node world
/// transforms can carry non-uniform scale) and a material built by the caller.
#[allow(clippy::too_many_arguments)]
pub fn mesh_entity(
    asset_prefix: &str,
    mesh_stem: &str,
    material_fields: Vec<(&'static str, Value)>,
    entity_name: &str,
    translation: [f32; 3],
    rotation: [f32; 4],
    scale: [f32; 3],
    collider_stem: Option<&str>,
) -> Entity {
    let mut components = Vec::new();
    // Entity `Name` (source `Node.Material`), for debugging and authoring.
    if !entity_name.is_empty() {
        components.push(name(entity_name));
    }
    components.extend([
        transform(translation, Some(rotation), Some(scale)),
        mesh(asset_prefix, mesh_stem),
        material(material_fields),
    ]);
    if let Some(stem) = collider_stem {
        components.push(collider(asset_prefix, stem));
    }
    Entity {
        components,
        children: Vec::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prints_what_the_loader_parses() {
        let text = scene(
            "kit",
            Vec::new(),
            vec![
                mesh_entity(
                    "kit",
                    "a",
                    vec![("perceptual_roughness", Value::Float(0.25))],
                    "A \"quoted\".Mat",
                    [0.1, 0.0, -2.0],
                    [0.0, 0.0, 0.0, 1.0],
                    [1.0; 3],
                    Some("a"),
                ),
                Entity {
                    components: vec![name("B"), scene_ref("other/b.bsn")],
                    children: vec![Entity {
                        components: vec![skin_joints(vec!["hip".into(), "knee".into()])],
                        children: Vec::new(),
                    }],
                },
            ],
        );
        let doc = bevy::bsn::parse(&text).unwrap_or_else(|e| panic!("{e}\n{text}"));
        assert_eq!(doc.roots.len(), 1);
        assert!(text.contains("x: 0.1,") && text.contains("--"), "{text}");
        assert!(text.contains(r#"Name("A \"quoted\".Mat")"#), "{text}");
    }
}
