//! G1 rig importer: bake each MotionBricks G1 link `.glb` → a named `.cluster_mesh`, and emit
//! `g1.bsn` — a reusable rig template (`G1Rig` root carrying the mujoco z-up→bevy y-up rotation,
//! one `G1Link` child per geom with its baked mesh + flat solari material). zero's `BodyPlugin`
//! drives it: `drive_links` writes each child's `Transform` from the FK'd qpos every frame, so the
//! `.bsn` only seeds the prefab (offsets live on `G1Link`, not the Transform).
//!
//!   cargo run --release -p g1_import -- /mnt/code/p/zero/assets ai/motionbricks/g1

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use bevy::math::{Mat3, Quat, Vec3};
use clap::Parser;
use serde::Deserialize;
use aurora_bsn::gltf::bake_glb_primitive;

#[derive(Parser)]
#[command(about = "Bake the G1 rig glbs → .cluster_mesh + g1.bsn template")]
struct Args {
    /// zero's asset root — the dir the asset-server paths are relative to.
    assets_root: PathBuf,
    /// Asset-relative dir holding `g1_links.json` + the link glbs (outputs land here too).
    #[arg(default_value = "ai/motionbricks/g1")]
    prefix: String,
    /// Re-bake `.cluster_mesh` files even if they already exist.
    #[arg(long)]
    replace: bool,
}

#[derive(Deserialize)]
struct Link {
    index: usize,
    name: String,
    geoms: Vec<Geom>,
}

#[derive(Deserialize)]
struct Geom {
    /// Asset-relative glb, e.g. `ai/motionbricks/g1/pelvis.glb`.
    glb: String,
    pos: [f32; 3],
    /// wxyz.
    quat: [f32; 4],
    rgba: [f32; 4],
}

/// Fixed-point float literal — the `.bsn` lexer rejects scientific notation.
fn f(x: f32) -> String {
    format!("{x:.6}")
}

fn main() {
    let args = Args::parse();
    let dir = args.assets_root.join(&args.prefix);
    let manifest: Vec<Link> = serde_json::from_str(
        &fs::read_to_string(dir.join("g1_links.json")).expect("read g1_links.json"),
    )
    .expect("parse g1_links.json");

    let meshes_dir = dir.join("meshes");
    let mut baked = 0usize;
    let mut children = String::new();

    for link in &manifest {
        for (gi, geom) in link.geoms.iter().enumerate() {
            let stem = PathBuf::from(&geom.glb)
                .file_stem()
                .expect("glb has a stem")
                .to_string_lossy()
                .into_owned();
            let out = meshes_dir.join(format!("{stem}.cluster_mesh"));
            match bake_glb_primitive(&args.assets_root.join(&geom.glb), &out, args.replace) {
                Ok(true) => baked += 1,
                Ok(false) => {}
                Err(e) => panic!("bake {stem}: {e}"),
            }

            // manifest quat is wxyz → glam xyzw; rgba is sRGB.
            let (qx, qy, qz, qw) = (geom.quat[1], geom.quat[2], geom.quat[3], geom.quat[0]);
            let [r, g, b, a] = geom.rgba;
            // camera anchor: the torso's primary geom (the G1 has no separate head bone)
            let head = if link.name == "torso_link" && gi == 0 {
                "    ai::model::body::plugin::G1Head\n"
            } else {
                ""
            };
            let _ = write!(
                children,
                "    bevy_ecs::name::Name(\"{}#{gi}\")\n    \
                 bevy_transform::components::transform::Transform {{ translation: glam::DVec3 {{ x: 0.0, y: 0.0, z: 0.0 }}, rotation: glam::DQuat {{ x: 0.0, y: 0.0, z: 0.0, w: 1.0 }}, scale: glam::DVec3 {{ x: 1.0, y: 1.0, z: 1.0 }} }}\n    \
                 ai::model::body::plugin::G1Link {{ index: {}, offset_pos: glam::Vec3 {{ x: {}, y: {}, z: {} }}, offset_rot: glam::Quat {{ x: {}, y: {}, z: {}, w: {} }} }}\n{head}    \
                 bevy_aurora::bindings::types::RaytracingMesh3d(\"{}/meshes/{stem}.cluster_mesh\")\n    \
                 bevy_aurora::material::AuroraMaterial3d(bevy_aurora::material::StandardAuroraMaterial {{ base_color: bevy_color::color::Color::Srgba(bevy_color::srgba::Srgba {{ red: {}, green: {}, blue: {}, alpha: {} }}), metallic: {}, perceptual_roughness: {} }}),\n\n",
                link.name,
                link.index,
                f(geom.pos[0]), f(geom.pos[1]), f(geom.pos[2]),
                f(qx), f(qy), f(qz), f(qw),
                args.prefix,
                f(r), f(g), f(b), f(a),
                f(0.5), f(0.55),
            );
        }
    }

    // Root carries mujoco z-up → bevy y-up (same basis swap as examples/body.rs). Transform is f64
    // in the fork, so it MUST be written as `glam::DQuat` — an f32 literal silently zeroes.
    let [zx, zy, zz, zw] = Quat::from_mat3(&Mat3::from_cols(Vec3::Z, Vec3::X, Vec3::Y)).to_array();
    let bsn = format!(
        "// Generated by g1_import. Do not edit by hand.\n\
         #g1\n\
         ai::model::body::plugin::G1Rig\n\
         bevy_transform::components::transform::Transform {{ rotation: glam::DQuat {{ x: {}, y: {}, z: {}, w: {} }} }}\n\
         bevy_ecs::hierarchy::Children [\n{children}]\n",
        f(zx), f(zy), f(zz), f(zw),
    );
    let bsn_path = dir.join("g1.bsn");
    fs::write(&bsn_path, bsn).expect("write g1.bsn");
    println!("baked {baked} cluster meshes; wrote {}", bsn_path.display());
}
